### ISSUE TITLE
Relation multiplicity produces incorrect array nullability

### ISSUE THREAD

**Issue by marco-giancotti** [orefalo/StarUML-GraphQL#1] opened 2017-06-01 03:53 UTC
Awesome plugin!

When the multiplicity of a relation is `0` or `1`, the object is assigned the correct nullability (with and without the `!` respectively). However, when using variable multiplicities starting from 1 like `1..*` the result should be, `[type!]`, not the `[type]!` returned by the plugin.

Sometimes developers may want an attribute to *always* contain a list, but that list can be empty. Right now to achieve that, they have to set the multiplicity to `1..*`, which is counter-intuitive for something that can contain 0 instances. Conversely, I could not find a way to produce a nullable list with non-nullable elements, i.e. `[type!]`.

The latter problem can be solved by changing one line [here](https://github.com/orefalo/StarUML-GraphQL/blob/d05676f03bb13b6d486fd94cb8fd078e22e36f51/GraphQLCodeGenerator.js#L540), but then we would need a totally new way to produce `[type]!`. Perhaps using a custom "required" qualifier?

**Comment by orefalo** [comment] 2017-06-26 15:26
Marco, sorry about the delay only reading this now.  let me read this in more details.

Also, I have an enhanced version with gql generation in a staruml view.

**Comment by orefalo** [comment] 2017-06-26 15:32
0...1 -> type
1 -> type!
1...* / n...* -> [type!]
0...* / * -> [type]

am I missing anything?

**Comment by marco-giancotti** [comment] 2017-06-27 03:49
Just one:

??? -> [type]!

which means "non-nullable list containing nullable objects".

You can see it mentione [here][1], for instance:
> [Episode]! represents an array of Episode objects. Since it is also non-nullable, you can always expect an array (with zero or more items) when you query the appearsIn field.

[1]: http://graphql.org/learn/schema/

**Comment by orefalo** [comment] 2017-06-27 13:11
Of course, I get it, the issue is that we are getting to the limits of the modeling tool, and to some extends, UML.

Let's try to enumerate all the scenarios. 
This is how it could work:

  | Cardinality property|  => Generation
  | ------------------- |--------------|
  |       0..1          |        field |
  |       0..1!         |       field! |
  |       1             |       field! |
  |       1!            |       field! |
  |       0..* or *     |      [field] |
  |       0..*! or *!   |     [field]! |
  |       1..*          |     [field!] |
  |       1..*!         |    [field!]! | 

What do you think?

**Comment by orefalo** [comment] 2017-06-27 21:53
ok I have it ready. should be updating submitting tomorrow as follows.

| Cardinality property|  => Generation |
| ------------------- |--------------|
|       0..1          |        field |
|       0..1!         |       field! |
|       n   n>0       |       field! |
|       n!  n>0       |       field! |
|       0..* or *     |      [field] |
|       0..*! or *!   |     [field]! |
|       1..*          |     [field!] |
|       1..*!         |    [field!]! |

**Comment by marco-giancotti** [comment] 2017-06-28 03:39
Good idea using `!` in the property, I didn't know it was possible.

2017年6月28日(水) 6:53 Olivier Refalo <notifications@github.com>:

**Comment by orefalo** [comment] 2017-06-28 04:36
Actually, it doesn't work.

I mean... It does, but then starUML is lost when you change the entity name (using the modeling view), it can't parse these new relationship types, like "0..*!".  Anyways, I just submitted version 1.0.3 which partially fixes this issue along with great other visual improvements.

I tried to fix this issue with cardinalities, and stereotypes, both didn't give me an acceptable solution, wither from a visual standpoint or behavior angle. I also opened a ticket with starUML in order to add a "isRequired" property.

I will close this ticket and open a more precise issue for [field!]! generation

Thank you

**Closed as completed by orefalo** 2017-06-28 04:36 UTC
